name: Dive tool good dockerfile
on:
  push:
    branches:
      - master

jobs:
  dive-docker:
    name: Build Python Img
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out source code
      uses: actions/checkout@master
      with:
          fetch-depth: 1

    - name: Build good docker example
      timeout-minutes: 10
      run: |
        docker build . \
        --file good-dockerfile/Dockerfile \
        --tag dive-python-poc-good

    - name: Explore docker image
      timeout-minutes: 2
      env:
        CI: "true"
      run: |
        wget -qO- https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.tar.gz | sudo tar xvz -C /usr/local/bin
        dive --ci-config "${{ github.workspace }}/.dive-ci" dive-python-poc-good
